modLoader="javafml" 
loaderVersion="[36,)" 
license="MIT"
[[mods]] 
modId="firstmod" 
version="${file.jarVersion}" 
displayName="First Mod" 
logoFile="examplemod.png" 
credits="First Mod by CheeseMan" 
description='''
First Mod of CheeseMan.
'''
[[dependencies.firstmod]] 
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.firstmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
